[web]
3.111.144.62 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ec2-user/my-key.pem

[app]
10.0.10.160 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ec2-user/my-key.pem ansible_ssh_common_args='-o ProxyCommand="ssh -i /home/ec2-user/my-key.pem ubuntu@3.111.144.62 -W %h:%p"'